import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-white">
          <nav
            className="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8"
            aria-label="Global"
          >
            <Link className="flex lg:flex-1" href="/">
              <h2 className="text-black font-bold">Notes</h2>
            </Link>

            <div className="lg:flex lg:flex-1 lg:justify-end">
              <Link
                href="/create"
                className="text-sm font-semibold leading-6 text-gray-900"
              >
                Create Note <span aria-hidden="true">&rarr;</span>
              </Link>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
